server:
  port: 8083

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    # username y password NO se definen aquí; vendrán del Key Vault en el bean
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  sql:
    init:
      mode: never

  jta:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ebechd8p85cw3p1x.us.auth0.com/  # TODO completar dominio Auth0 (con barra final)

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.azure.identity: INFO
    reactor.netty: WARN

jwt:
  expected-audience: https://api.uco-challenge            # TODO completar con el Identifier de Auth0

security:
  gateway:
    hmac-secret: ${GATEWAY_HMAC_SECRET:4F39B2E91A8D44C2B28C937A7F84E72F}

external:
  parameters:
    base-url: http://localhost:8080/parameters/api/v1/parameters
  messages:
    base-url: http://localhost:8081/messages/api/v1/messages

azure:
  keyvault:
    url: https://uco-vault.vault.azure.net/
  secrets:
    client-id: client-id
    client-secret: client-secret
