server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect es opcional en Spring Boot 3; puedes dejarlo así o activarlo si lo prefieres
        # dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
