server:
  port: 8083

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    # username y password NO se definen aquí; vendrán del Key Vault en el bean
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  sql:
    init:
      mode: never

  jta:
    enabled: false

azure:
  keyvault:
    url: https://uco-vault.vault.azure.net/

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.azure.identity: INFO
    reactor.netty: WARN
